### ISSUE TITLE
Download link broken

### ISSUE THREAD

**Issue by noirmist** [ZhichenZhao/part-action-network#1]
Hi,
I found your download link is broken in the readme file.
Detailed position is express as bold & italic below
____________________________________________________________________________________________________
Annotations
The annotations are provided as "txt" files, in each of them, we label part actions in order of head-torso-lower_body-left_arm-right_arm-left_hand-right_hand. Since in any case you need to locate part locations in the test phase by algprithms, we do not provide part locations in the training set, which keeps consistency for the part localization.

Download the annotations: **_Annotations_**

Models
you can download the model from my google drive: **_PAN of Stanford40_**

**Comment by ZhichenZhao** [comment]
hi @noirmist,
sorry for that, I uploaded the files on my company's google drive but now we are on Office 365. Now I generate share links for them. You can verify whether it works. If you find any problems, just contact me.

**Comment by noirmist** [comment]
Thanks! 
Now I can download it.

**Comment by samarmahmou** [comment]
@noirmist
I have the same problem.
how you solved it?
