### ISSUE TITLE
The Annotations file not found?

### ISSUE THREAD

**Issue by samarmahmou** [ZhichenZhao/part-action-network#2]
The annotation file for stanford40 has deleted
can you load it again?

**Comment by ZhichenZhao** [comment]
@samarmahmou hi, I have uploaded the annotations and the model. Please tell me if there are any problems~

**Comment by samarmahmou** [comment]
hi,@ZhichenZhao I try to download them now but also not work...?!

**Comment by ZhichenZhao** [comment]
> hi,@ZhichenZhao I try to download them now but also not work...?!

hi, I guess maybe there are problems when visiting Baidu. I add google drive links. Please check it.

**Comment by samarmahmou** [comment]
thanks alot.
